# Generated by Django 4.0.6 on 2022-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='email',
            field=models.CharField(default=None, max_length=10, null=True, unique=True),
        ),
    ]
