# Generated by Django 4.0.6 on 2022-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='apifiles')),
            ],
            options={
                'db_table': 'user_files',
            },
        ),
    ]
