services:
  jenkins:
    image: jenkins/jenkins:2.346.2
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  jenkins-data:



#version: '2'
#services:
#  jenkins:
#    image: jenkins/jenkins:2.346.2
#    container_name: jenkins
#    ports:
#      - 8080:8080
#      - 50000:50000
#    restart: unless-stopped
#    environment:
#      - TZ=Asia/Kolkata
#    volumes:
#      - jenkins-data:/var/jenkins_home
#      - /var/run/docker.sock:/var/run/docker.sock
#
#volumes:
#  jenkins-data:
#    driver: local